services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fantasy_football
      POSTGRES_USER: fantasy_user
      POSTGRES_PASSWORD: fantasy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantasy_user -d fantasy_football"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fantasy_user:fantasy_password@postgres:5432/fantasy_football
      - REDIS_URL=redis://redis:6379/0
      - FANTASYPROS_API_KEY=${FANTASYPROS_API_KEY:-}
      - SLEEPER_USER_ID=${SLEEPER_USER_ID:-}
      - SLEEPER_LEAGUE_ID=${SLEEPER_LEAGUE_ID:-}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Temporarily commented out until we create the tasks module
  # celery-worker:
  #   build: ./backend
  #   environment:
  #     - DATABASE_URL=postgresql://fantasy_user:fantasy_password@postgres:5432/fantasy_football
  #     - REDIS_URL=redis://redis:6379/0
  #     - FANTASYPROS_API_KEY=${FANTASYPROS_API_KEY:-}
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./backend:/app
  #   command: celery -A app.tasks.celery worker --loglevel=info

  # celery-beat:
  #   build: ./backend
  #   environment:
  #     - DATABASE_URL=postgresql://fantasy_user:fantasy_password@postgres:5432/fantasy_football
  #     - REDIS_URL=redis://redis:6379/0
  #     - FANTASYPROS_API_KEY=${FANTASYPROS_API_KEY:-}
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./backend:/app
  #   command: celery -A app.tasks.celery beat --loglevel=info

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: