"""Add comprehensive fantasy scoring   fields

Revision ID: 333989a73707
Revises: 63045796c080
Create Date: 2025-09-16 21:40:51.325272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333989a73707'
down_revision: Union[str, None] = '63045796c080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleeper_player_stats', sa.Column('pass_2pt', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('rush_2pt', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('rec_2pt', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_2pt', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fum', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fum_lost', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pass_sack', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('ff', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fum_rec_td', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('bonus_rec_te', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_0_19', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_20_29', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_30_39', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_40_49', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_50_59', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_60p', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgmiss_0_19', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgmiss_20_29', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgmiss_30_39', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgmiss_40_49', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('fgm_yds', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('xpmiss', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_0', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_1_6', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_7_13', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_14_20', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_21_27', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_28_34', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow_35p', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_0_100', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_100_199', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_200_299', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_300_349', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_350_399', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_400_449', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_450_499', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_500_549', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow_550p', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_4_and_stop', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_st_td', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_st_fum_rec', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_st_ff', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('idp_tkl', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('kr_yd', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pr_yd', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('st_td', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('st_fum_rec', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('st_ff', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('pts_allow', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('yds_allow', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleeper_player_stats', 'yds_allow')
    op.drop_column('sleeper_player_stats', 'pts_allow')
    op.drop_column('sleeper_player_stats', 'st_ff')
    op.drop_column('sleeper_player_stats', 'st_fum_rec')
    op.drop_column('sleeper_player_stats', 'st_td')
    op.drop_column('sleeper_player_stats', 'pr_yd')
    op.drop_column('sleeper_player_stats', 'kr_yd')
    op.drop_column('sleeper_player_stats', 'idp_tkl')
    op.drop_column('sleeper_player_stats', 'def_st_ff')
    op.drop_column('sleeper_player_stats', 'def_st_fum_rec')
    op.drop_column('sleeper_player_stats', 'def_st_td')
    op.drop_column('sleeper_player_stats', 'def_4_and_stop')
    op.drop_column('sleeper_player_stats', 'yds_allow_550p')
    op.drop_column('sleeper_player_stats', 'yds_allow_500_549')
    op.drop_column('sleeper_player_stats', 'yds_allow_450_499')
    op.drop_column('sleeper_player_stats', 'yds_allow_400_449')
    op.drop_column('sleeper_player_stats', 'yds_allow_350_399')
    op.drop_column('sleeper_player_stats', 'yds_allow_300_349')
    op.drop_column('sleeper_player_stats', 'yds_allow_200_299')
    op.drop_column('sleeper_player_stats', 'yds_allow_100_199')
    op.drop_column('sleeper_player_stats', 'yds_allow_0_100')
    op.drop_column('sleeper_player_stats', 'pts_allow_35p')
    op.drop_column('sleeper_player_stats', 'pts_allow_28_34')
    op.drop_column('sleeper_player_stats', 'pts_allow_21_27')
    op.drop_column('sleeper_player_stats', 'pts_allow_14_20')
    op.drop_column('sleeper_player_stats', 'pts_allow_7_13')
    op.drop_column('sleeper_player_stats', 'pts_allow_1_6')
    op.drop_column('sleeper_player_stats', 'pts_allow_0')
    op.drop_column('sleeper_player_stats', 'xpmiss')
    op.drop_column('sleeper_player_stats', 'fgm_yds')
    op.drop_column('sleeper_player_stats', 'fgmiss_40_49')
    op.drop_column('sleeper_player_stats', 'fgmiss_30_39')
    op.drop_column('sleeper_player_stats', 'fgmiss_20_29')
    op.drop_column('sleeper_player_stats', 'fgmiss_0_19')
    op.drop_column('sleeper_player_stats', 'fgm_60p')
    op.drop_column('sleeper_player_stats', 'fgm_50_59')
    op.drop_column('sleeper_player_stats', 'fgm_40_49')
    op.drop_column('sleeper_player_stats', 'fgm_30_39')
    op.drop_column('sleeper_player_stats', 'fgm_20_29')
    op.drop_column('sleeper_player_stats', 'fgm_0_19')
    op.drop_column('sleeper_player_stats', 'bonus_rec_te')
    op.drop_column('sleeper_player_stats', 'fum_rec_td')
    op.drop_column('sleeper_player_stats', 'ff')
    op.drop_column('sleeper_player_stats', 'pass_sack')
    op.drop_column('sleeper_player_stats', 'fum_lost')
    op.drop_column('sleeper_player_stats', 'fum')
    op.drop_column('sleeper_player_stats', 'def_2pt')
    op.drop_column('sleeper_player_stats', 'rec_2pt')
    op.drop_column('sleeper_player_stats', 'rush_2pt')
    op.drop_column('sleeper_player_stats', 'pass_2pt')
    # ### end Alembic commands ###
