"""consolidate_players_and_sleeper_players_tables

Revision ID: 4b8eff535bb8
Revises: 333989a73707
Create Date: 2025-09-17 14:28:09.862854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8eff535bb8'
down_revision: Union[str, None] = '333989a73707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add new columns to players table (skip existing columns)
    op.add_column('players', sa.Column('full_name', sa.String(length=100), nullable=True))  # Temporarily nullable
    op.add_column('players', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('team', sa.String(length=10), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('height', sa.String(length=10), nullable=True))
    op.add_column('players', sa.Column('weight', sa.String(length=10), nullable=True))
    op.add_column('players', sa.Column('college', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('years_exp', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('status', sa.Enum('Active', 'Inactive', 'Injured Reserve', 'Reserve/PUP', 'Practice Squad', 'Free Agent', name='player_status'), nullable=True))
    op.add_column('players', sa.Column('fantasy_positions', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('sleeper_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('espn_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('yahoo_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('fantasy_data_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('rotowire_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('stats_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('nfl_gsis_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('pfr_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('primary_data_source', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('data_quality_score', sa.DECIMAL(precision=3, scale=2), nullable=True))
    # Note: injury_status, bye_week, created_at, updated_at already exist

    # Temporarily make nfl_team nullable for migration
    op.alter_column('players', 'nfl_team', nullable=True)

    # Migrate data from old players table to new structure (preserve existing data)
    op.execute("""
        UPDATE players SET
            full_name = name,
            team = nfl_team,
            years_exp = years_pro,
            sleeper_id = player_id,
            primary_data_source = 'sleeper',
            data_quality_score = 1.00
        WHERE full_name IS NULL
    """)

    # Insert data from sleeper_players table that doesn't exist in players
    # Use sleeper_player_id as the new player_id (primary key)
    op.execute("""
        INSERT INTO players (
            player_id, name, position, nfl_team, full_name, first_name, last_name, team, age, height, weight,
            college, years_exp, status, fantasy_positions, sleeper_id, espn_id, yahoo_id,
            fantasy_data_id, rotowire_id, stats_id, primary_data_source, last_updated,
            data_quality_score, injury_status, bye_week, created_at, updated_at
        )
        SELECT
            sp.sleeper_player_id,
            COALESCE(sp.full_name, sp.first_name || ' ' || sp.last_name, 'Unknown'),
            COALESCE(sp.position, 'UNK'),
            CASE
                WHEN sp.team IS NOT NULL AND EXISTS(SELECT 1 FROM nfl_teams WHERE team_code = sp.team)
                THEN sp.team
                ELSE NULL
            END,
            sp.full_name,
            sp.first_name,
            sp.last_name,
            CASE
                WHEN sp.team = 'OAK' THEN 'LV'  -- Oakland Raiders moved to Las Vegas
                ELSE sp.team
            END,
            sp.age,
            sp.height,
            sp.weight,
            sp.college,
            sp.years_exp,
            sp.status,
            sp.fantasy_positions,
            sp.sleeper_player_id,
            sp.espn_id,
            sp.yahoo_id,
            sp.fantasy_data_id,
            sp.rotowire_id,
            sp.stats_id,
            'sleeper',
            sp.last_updated,
            1.00,
            NULL,
            NULL,
            COALESCE(sp.created_at, NOW()),
            COALESCE(sp.updated_at, NOW())
        FROM sleeper_players sp
        WHERE sp.sleeper_player_id NOT IN (SELECT player_id FROM players WHERE player_id IS NOT NULL)
    """)

    # Update existing players with better data from sleeper_players where available
    op.execute("""
        UPDATE players p SET
            full_name = COALESCE(sp.full_name, p.full_name),
            first_name = COALESCE(sp.first_name, p.first_name),
            last_name = COALESCE(sp.last_name, p.last_name),
            position = COALESCE(sp.position, p.position),
            team = COALESCE(
                CASE
                    WHEN sp.team = 'OAK' THEN 'LV'
                    ELSE sp.team
                END,
                p.team
            ),
            age = COALESCE(sp.age, p.age),
            height = COALESCE(sp.height, p.height),
            weight = COALESCE(sp.weight, p.weight),
            college = COALESCE(sp.college, p.college),
            years_exp = COALESCE(sp.years_exp, p.years_exp),
            status = COALESCE(sp.status, p.status),
            fantasy_positions = COALESCE(sp.fantasy_positions, p.fantasy_positions),
            espn_id = COALESCE(sp.espn_id, p.espn_id),
            yahoo_id = COALESCE(sp.yahoo_id, p.yahoo_id),
            fantasy_data_id = COALESCE(sp.fantasy_data_id, p.fantasy_data_id),
            rotowire_id = COALESCE(sp.rotowire_id, p.rotowire_id),
            stats_id = COALESCE(sp.stats_id, p.stats_id),
            last_updated = COALESCE(sp.last_updated, p.last_updated),
            updated_at = sp.updated_at
        FROM sleeper_players sp
        WHERE p.sleeper_id = sp.sleeper_player_id OR p.player_id = sp.player_id
    """)

    # Update foreign key constraints to point to consolidated players table BEFORE dropping sleeper_players
    op.drop_constraint('sleeper_player_projections_sleeper_player_id_fkey', 'sleeper_player_projections', type_='foreignkey')
    op.create_foreign_key(None, 'sleeper_player_projections', 'players', ['sleeper_player_id'], ['player_id'])
    op.drop_constraint('sleeper_player_stats_sleeper_player_id_fkey', 'sleeper_player_stats', type_='foreignkey')
    op.create_foreign_key(None, 'sleeper_player_stats', 'players', ['sleeper_player_id'], ['player_id'])

    # Now drop the sleeper_players table
    op.drop_index('ix_sleeper_players_espn_id', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_fantasy_data_id', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_full_name', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_player_id', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_position', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_rotowire_id', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_stats_id', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_team', table_name='sleeper_players')
    op.drop_index('ix_sleeper_players_yahoo_id', table_name='sleeper_players')
    op.drop_table('sleeper_players')

    # Make full_name NOT NULL after data migration
    op.alter_column('players', 'full_name', nullable=False)
    op.drop_index('ix_players_name', table_name='players')
    op.drop_index('ix_players_nfl_team', table_name='players')
    op.create_index(op.f('ix_players_espn_id'), 'players', ['espn_id'], unique=False)
    op.create_index(op.f('ix_players_fantasy_data_id'), 'players', ['fantasy_data_id'], unique=False)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index('ix_players_name_position', 'players', ['full_name', 'position'], unique=False)
    op.create_index(op.f('ix_players_nfl_gsis_id'), 'players', ['nfl_gsis_id'], unique=False)
    op.create_index(op.f('ix_players_pfr_id'), 'players', ['pfr_id'], unique=False)
    op.create_index('ix_players_position_team', 'players', ['position', 'team'], unique=False)
    op.create_index(op.f('ix_players_rotowire_id'), 'players', ['rotowire_id'], unique=False)
    op.create_index(op.f('ix_players_sleeper_id'), 'players', ['sleeper_id'], unique=False)
    op.create_index(op.f('ix_players_stats_id'), 'players', ['stats_id'], unique=False)
    op.create_index(op.f('ix_players_status'), 'players', ['status'], unique=False)
    op.create_index('ix_players_status_position', 'players', ['status', 'position'], unique=False)
    op.create_index(op.f('ix_players_team'), 'players', ['team'], unique=False)
    op.create_index(op.f('ix_players_yahoo_id'), 'players', ['yahoo_id'], unique=False)
    op.drop_constraint('players_nfl_team_fkey', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'nfl_teams', ['team'], ['team_code'])
    op.drop_column('players', 'nfl_team')
    op.drop_column('players', 'years_pro')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sleeper_player_stats', type_='foreignkey')
    op.create_foreign_key('sleeper_player_stats_sleeper_player_id_fkey', 'sleeper_player_stats', 'sleeper_players', ['sleeper_player_id'], ['sleeper_player_id'])
    op.drop_constraint(None, 'sleeper_player_projections', type_='foreignkey')
    op.create_foreign_key('sleeper_player_projections_sleeper_player_id_fkey', 'sleeper_player_projections', 'sleeper_players', ['sleeper_player_id'], ['sleeper_player_id'])
    op.add_column('players', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('years_pro', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('nfl_team', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('players_nfl_team_fkey', 'players', 'nfl_teams', ['nfl_team'], ['team_code'])
    op.drop_index(op.f('ix_players_yahoo_id'), table_name='players')
    op.drop_index(op.f('ix_players_team'), table_name='players')
    op.drop_index('ix_players_status_position', table_name='players')
    op.drop_index(op.f('ix_players_status'), table_name='players')
    op.drop_index(op.f('ix_players_stats_id'), table_name='players')
    op.drop_index(op.f('ix_players_sleeper_id'), table_name='players')
    op.drop_index(op.f('ix_players_rotowire_id'), table_name='players')
    op.drop_index('ix_players_position_team', table_name='players')
    op.drop_index(op.f('ix_players_pfr_id'), table_name='players')
    op.drop_index(op.f('ix_players_nfl_gsis_id'), table_name='players')
    op.drop_index('ix_players_name_position', table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_fantasy_data_id'), table_name='players')
    op.drop_index(op.f('ix_players_espn_id'), table_name='players')
    op.create_index('ix_players_nfl_team', 'players', ['nfl_team'], unique=False)
    op.create_index('ix_players_name', 'players', ['name'], unique=False)
    op.drop_column('players', 'data_quality_score')
    op.drop_column('players', 'last_updated')
    op.drop_column('players', 'primary_data_source')
    op.drop_column('players', 'pfr_id')
    op.drop_column('players', 'nfl_gsis_id')
    op.drop_column('players', 'stats_id')
    op.drop_column('players', 'rotowire_id')
    op.drop_column('players', 'fantasy_data_id')
    op.drop_column('players', 'yahoo_id')
    op.drop_column('players', 'espn_id')
    op.drop_column('players', 'sleeper_id')
    op.drop_column('players', 'fantasy_positions')
    op.drop_column('players', 'status')
    op.drop_column('players', 'years_exp')
    op.drop_column('players', 'college')
    op.drop_column('players', 'weight')
    op.drop_column('players', 'height')
    op.drop_column('players', 'age')
    op.drop_column('players', 'team')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    op.drop_column('players', 'full_name')
    op.create_table('sleeper_players',
    sa.Column('sleeper_player_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('weight', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('college', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('years_exp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Active', 'Inactive', 'Injured Reserve', 'Reserve/PUP', name='player_status'), autoincrement=False, nullable=True),
    sa.Column('fantasy_positions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('espn_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rotowire_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fantasy_data_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('yahoo_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('stats_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='sleeper_players_player_id_fkey'),
    sa.PrimaryKeyConstraint('sleeper_player_id', name='sleeper_players_pkey')
    )
    op.create_index('ix_sleeper_players_yahoo_id', 'sleeper_players', ['yahoo_id'], unique=False)
    op.create_index('ix_sleeper_players_team', 'sleeper_players', ['team'], unique=False)
    op.create_index('ix_sleeper_players_stats_id', 'sleeper_players', ['stats_id'], unique=False)
    op.create_index('ix_sleeper_players_rotowire_id', 'sleeper_players', ['rotowire_id'], unique=False)
    op.create_index('ix_sleeper_players_position', 'sleeper_players', ['position'], unique=False)
    op.create_index('ix_sleeper_players_player_id', 'sleeper_players', ['player_id'], unique=False)
    op.create_index('ix_sleeper_players_full_name', 'sleeper_players', ['full_name'], unique=False)
    op.create_index('ix_sleeper_players_fantasy_data_id', 'sleeper_players', ['fantasy_data_id'], unique=False)
    op.create_index('ix_sleeper_players_espn_id', 'sleeper_players', ['espn_id'], unique=False)
    # ### end Alembic commands ###
