"""Add external ID columns to sleeper_players

Revision ID: 63045796c080
Revises: d883ba0a2ff1
Create Date: 2025-09-12 14:41:52.084571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63045796c080'
down_revision: Union[str, None] = 'd883ba0a2ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleeper_players', sa.Column('espn_id', sa.String(length=50), nullable=True))
    op.add_column('sleeper_players', sa.Column('rotowire_id', sa.String(length=50), nullable=True))
    op.add_column('sleeper_players', sa.Column('fantasy_data_id', sa.String(length=50), nullable=True))
    op.add_column('sleeper_players', sa.Column('yahoo_id', sa.String(length=50), nullable=True))
    op.add_column('sleeper_players', sa.Column('stats_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sleeper_players_espn_id'), 'sleeper_players', ['espn_id'], unique=False)
    op.create_index(op.f('ix_sleeper_players_fantasy_data_id'), 'sleeper_players', ['fantasy_data_id'], unique=False)
    op.create_index(op.f('ix_sleeper_players_rotowire_id'), 'sleeper_players', ['rotowire_id'], unique=False)
    op.create_index(op.f('ix_sleeper_players_stats_id'), 'sleeper_players', ['stats_id'], unique=False)
    op.create_index(op.f('ix_sleeper_players_yahoo_id'), 'sleeper_players', ['yahoo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeper_players_yahoo_id'), table_name='sleeper_players')
    op.drop_index(op.f('ix_sleeper_players_stats_id'), table_name='sleeper_players')
    op.drop_index(op.f('ix_sleeper_players_rotowire_id'), table_name='sleeper_players')
    op.drop_index(op.f('ix_sleeper_players_fantasy_data_id'), table_name='sleeper_players')
    op.drop_index(op.f('ix_sleeper_players_espn_id'), table_name='sleeper_players')
    op.drop_column('sleeper_players', 'stats_id')
    op.drop_column('sleeper_players', 'yahoo_id')
    op.drop_column('sleeper_players', 'fantasy_data_id')
    op.drop_column('sleeper_players', 'rotowire_id')
    op.drop_column('sleeper_players', 'espn_id')
    # ### end Alembic commands ###
