"""Add defensive stats columns to sleeper_player_stats

Revision ID: 6464334c1dd3
Revises: 
Create Date: 2025-09-11 17:10:17.149112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6464334c1dd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_impact_analysis_news_event_id', table_name='news_impact_analysis')
    op.drop_index('ix_news_impact_analysis_player_id', table_name='news_impact_analysis')
    op.drop_table('news_impact_analysis')
    op.create_foreign_key(None, 'news_events', 'players', ['player_id'], ['player_id'])
    op.create_foreign_key(None, 'news_events', 'sources', ['source_id'], ['source_id'])
    op.add_column('sleeper_player_stats', sa.Column('def_sack', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_int', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_fumble_rec', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_td', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_safety', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_block_kick', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_pass_def', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_tackle_solo', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_tackle_assist', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_qb_hit', sa.Integer(), nullable=True))
    op.add_column('sleeper_player_stats', sa.Column('def_tfl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleeper_player_stats', 'def_tfl')
    op.drop_column('sleeper_player_stats', 'def_qb_hit')
    op.drop_column('sleeper_player_stats', 'def_tackle_assist')
    op.drop_column('sleeper_player_stats', 'def_tackle_solo')
    op.drop_column('sleeper_player_stats', 'def_pass_def')
    op.drop_column('sleeper_player_stats', 'def_block_kick')
    op.drop_column('sleeper_player_stats', 'def_safety')
    op.drop_column('sleeper_player_stats', 'def_td')
    op.drop_column('sleeper_player_stats', 'def_fumble_rec')
    op.drop_column('sleeper_player_stats', 'def_int')
    op.drop_column('sleeper_player_stats', 'def_sack')
    op.drop_constraint(None, 'news_events', type_='foreignkey')
    op.drop_constraint(None, 'news_events', type_='foreignkey')
    op.create_table('news_impact_analysis',
    sa.Column('impact_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('news_event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pre_event_avg_rank', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('post_event_avg_rank', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('rank_change', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('time_to_impact_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_accuracy_on_impact', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('impact_duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('impact_id', name='news_impact_analysis_pkey')
    )
    op.create_index('ix_news_impact_analysis_player_id', 'news_impact_analysis', ['player_id'], unique=False)
    op.create_index('ix_news_impact_analysis_news_event_id', 'news_impact_analysis', ['news_event_id'], unique=False)
    # ### end Alembic commands ###
