"""Add defensive stats columns to sleeper_player_stats

Revision ID: d883ba0a2ff1
Revises: 6464334c1dd3
Create Date: 2025-09-11 17:10:47.820980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd883ba0a2ff1'
down_revision: Union[str, None] = '6464334c1dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
